# Generated by Django 4.2.7 on 2023-11-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='Evento',
        ),
    ]
